name: user_career_auth
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  user_career_core:
    path: ../user_career_core
  user_career_user:
    path: ../user_career_user
  auto_route: ^8.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  jwt_decoder: ^2.0.1
  pin_input_text_field: ^4.5.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0
  email_auth: ^2.0.0
  email_otp: ^3.0.2
  firebase_auth: ^5.2.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.2.14

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0

flutter:
