name: user_career_home
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  user_career_core:
    path: ../user_career_core
  user_career_user:
    path: ../user_career_user
  auto_route: ^8.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  calendar_date_picker2: ^1.1.5
  intl: ^0.19.0
  timelines: ^0.1.0
  riverpod_annotation: ^2.3.5
  flutter_datetime_picker_plus: ^2.2.0
  syncfusion_flutter_charts: ^26.2.5+1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0

flutter:
